name: Deployment pipeline

on:
  push:
    branches:
      - main

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          jest-version: '25.5.4'
      - name: npm install
        run: npm install
      - name: lint
        run : npm run eslint
      - name: build
        run : npm run build
      - name: test
        run : npm run jest